/*
 * a3net_ffi.h — C ABI for the A3Net mobile surface.
 *
 * AUTO-GENERATED by cbindgen. DO NOT EDIT.
 *
 * The Rust source lives in `crates/a3net-ffi/src/lib.rs` and
 * friends. Re-generate with:
 *
 *     cbindgen --config cbindgen.toml --crate a3net-ffi \
 *         --output include/a3net_ffi.h
 *
 * The header filename and `A3NET_FFI_H` include guard are
 * the canonical `a3net` brand. The previous `adnet` brand
 * is kept as deprecated Rust-level aliases; the generated
 * header only emits the canonical names (the [export]
 * `exclude` list filters the `Adnet*` aliases so we don't
 * double-emit the constants / structs).
 *
 * CI runs `cbindgen --verify` so a drift between the Rust
 * source and this header fails the build.
 */


#ifndef A3NET_FFI_H
#define A3NET_FFI_H

/* AUTO-GENERATED — regenerate with cbindgen. */


#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * A3Net FFI major version. Bumped when the C-ABI surface
 */
#define A3NET_FFI_VERSION 1

#define ADNET_FFI_VERSION A3NET_FFI_VERSION

#define InviteCode_CODE_LEN 16

/**
 * Current on-disk schema version.
 */
#define ContactsList_CURRENT_VERSION 1

#define BulletinId_HEX_LEN 64

#define ContentHash_HEX_LEN 64

#define MeshNetworkId_HEX_LEN MESH_NETWORK_ID_HEX_LEN

#define NodeId_HEX_LEN NODE_ID_HEX_LEN

#define Topic_HEX_LEN 64

/**
 * Maximum clock skew (in seconds) we accept from a peer's
 */
#define HeartbeatMessage_MAX_CLOCK_SKEW_SECS 300

/**
 * Current protocol version.
 */
#define HeartbeatMessage_VERSION 1

/**
 * Opaque handle to a tokio runtime + node. The FFI
 */
typedef struct A3netFfiHandle A3netFfiHandle;

/**
 * Individual capability flags.  Each variant represents a discrete
 */
typedef struct NodeCapability NodeCapability;

typedef struct Option_SubState Option_SubState;

/**
 * Stream priority for outgoing data.
 */
typedef struct StreamPriority StreamPriority;

/**
 * Data mode (permissions-like).
 */
typedef struct UnixFsMode UnixFsMode;

/**
 * Status code returned by every FFI function.
 */
typedef int32_t A3netFfiStatus;

/**
 * C-side opaque pointer to a heap-allocated byte buffer
 */
typedef struct A3netFfiBuffer {
    /**
     * Pointer to the first byte. NULL when the buffer is
     */
    char *a3net_ffi_nullable_ptr ptr;
    /**
     * Number of valid bytes at `ptr`. Zero on empty.
     */
    size_t len;
} A3netFfiBuffer;

#if defined(1)
/**
 * Per-room subscription handle. The mobile side keeps the
 */
typedef struct A3netNewsSubHandle {
    struct Option_SubState inner;
} A3netNewsSubHandle;
#endif

/**
 * A required feature was not enabled at build time (e.g. the
 */
#define A3NET_FFI_E_FEATURE -6

#if defined(1)
/**
 * Status code for "the `news` feature was not enabled at build
 */
#define A3NET_FFI_E_FEATURE_NEWS -10
#endif

/**
 * Caller passed a `NULL` pointer or an empty buffer.
 */
#define A3NET_FFI_E_INVALID_ARG -1

/**
 * The supplied JSON was malformed.
 */
#define A3NET_FFI_E_JSON -3

/**
 * Internal node error — see the human-readable error buffer.
 */
#define A3NET_FFI_E_NODE -4

/**
 * Profile read or update failed.
 */
#define A3NET_FFI_E_PROFILE -7

/**
 * Tokio runtime could not be created.
 */
#define A3NET_FFI_E_RUNTIME -5

/**
 * The supplied UTF-8 was not valid.
 */
#define A3NET_FFI_E_UTF8 -2

/**
 * `OK` — call succeeded; the out-buffer (if any) holds the result.
 */
#define A3NET_FFI_OK 0





























#if defined(1)
/**
 * The provenance string we stamp on every event the
 */
#define MdnsAddressLookup_PROVENANCE MDNS_PROVENANCE
#endif









#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

#if defined(1)
/**
 * Connect to a remote endpoint by its `NodeId` (raw 32-byte
 */
A3netFfiStatus a3net_ffi_dial(struct A3netFfiHandle *a3net_ffi_nullable_ptr handle,
                              const char *a3net_ffi_nullable_ptr nodeIdPtr,
                              size_t nodeIdLen,
                              struct A3netFfiBuffer *a3net_ffi_nullable_ptr out);
#endif

/**
 * Free a buffer previously returned by any FFI function.
 */
void a3net_ffi_free(struct A3netFfiBuffer buf);

/**
 * Compute the BLAKE3 `ContentHash` for a byte slice. The
 */
A3netFfiStatus a3net_ffi_hash_bytes(const char *a3net_ffi_nullable_ptr dataPtr,
                                    size_t dataLen,
                                    struct A3netFfiBuffer *a3net_ffi_nullable_ptr out);

#if defined(1)
/**
 * Return the iroh endpoint address of a node handle, ready
 */
A3netFfiStatus a3net_ffi_node_addr(struct A3netFfiHandle *a3net_ffi_nullable_ptr handle,
                                   struct A3netFfiBuffer *a3net_ffi_nullable_ptr out);
#endif

/**
 * Boot a node rooted at `data_dir` (UTF-8 path). The
 */
A3netFfiStatus a3net_ffi_node_create(const char *a3net_ffi_nullable_ptr dataDirPtr,
                                     size_t dataDirLen,
                                     struct A3netFfiBuffer *a3net_ffi_nullable_ptr out);

A3netFfiStatus a3net_ffi_node_destroy(struct A3netFfiHandle *a3net_ffi_nullable_ptr handle);

/**
 * Look up the local node's `NodeId`. Useful for the
 */
A3netFfiStatus a3net_ffi_node_id(struct A3netFfiHandle *a3net_ffi_nullable_ptr handle,
                                 struct A3netFfiBuffer *a3net_ffi_nullable_ptr out);

/**
 * Return the local node's profile as JSON.
 */
A3netFfiStatus a3net_ffi_node_profile(struct A3netFfiHandle *a3net_ffi_nullable_ptr handle,
                                      struct A3netFfiBuffer *a3net_ffi_nullable_ptr out);

/**
 * Return the local node's role label.
 */
A3netFfiStatus a3net_ffi_node_role(struct A3netFfiHandle *a3net_ffi_nullable_ptr handle,
                                   struct A3netFfiBuffer *a3net_ffi_nullable_ptr out);

/**
 * Add or update a contact. The payload is a JSON-encoded
 */
A3netFfiStatus a3net_ffi_roster_add_contact(const char *a3net_ffi_nullable_ptr dataDirPtr,
                                            size_t dataDirLen,
                                            const char *a3net_ffi_nullable_ptr payloadPtr,
                                            size_t payloadLen,
                                            struct A3netFfiBuffer *a3net_ffi_nullable_ptr out);

/**
 * Delete a contact by id. Returns `FfiResult<bool>` where `value`
 */
A3netFfiStatus a3net_ffi_roster_delete_contact(const char *a3net_ffi_nullable_ptr dataDirPtr,
                                               size_t dataDirLen,
                                               const char *a3net_ffi_nullable_ptr contactIdPtr,
                                               size_t contactIdLen,
                                               struct A3netFfiBuffer *a3net_ffi_nullable_ptr out);

/**
 * List every contact. Returns `FfiResult<Vec<Contact>>` where
 */
A3netFfiStatus a3net_ffi_roster_list_contacts(const char *a3net_ffi_nullable_ptr dataDirPtr,
                                              size_t dataDirLen,
                                              struct A3netFfiBuffer *a3net_ffi_nullable_ptr out);

/**
 * List every contact group. Returns `FfiResult<Vec<ContactGroup>>`.
 */
A3netFfiStatus a3net_ffi_roster_list_groups(const char *a3net_ffi_nullable_ptr dataDirPtr,
                                            size_t dataDirLen,
                                            struct A3netFfiBuffer *a3net_ffi_nullable_ptr out);

/**
 * Search contacts by case-insensitive substring over name / tags
 */
A3netFfiStatus a3net_ffi_roster_search_contacts(const char *a3net_ffi_nullable_ptr dataDirPtr,
                                                size_t dataDirLen,
                                                const char *a3net_ffi_nullable_ptr queryPtr,
                                                size_t queryLen,
                                                struct A3netFfiBuffer *a3net_ffi_nullable_ptr out);

/**
 * Compute and persist the 12-digit Exodus id for a `user_id`.
 */
A3netFfiStatus a3net_ffi_user_ensure_digit(const char *a3net_ffi_nullable_ptr dataDirPtr,
                                           size_t dataDirLen,
                                           const char *a3net_ffi_nullable_ptr userIdPtr,
                                           size_t userIdLen,
                                           struct A3netFfiBuffer *a3net_ffi_nullable_ptr out);

/**
 * Fetch a single profile by user_id. Returns
 */
A3netFfiStatus a3net_ffi_user_get_profile(const char *a3net_ffi_nullable_ptr dataDirPtr,
                                          size_t dataDirLen,
                                          const char *a3net_ffi_nullable_ptr userIdPtr,
                                          size_t userIdLen,
                                          struct A3netFfiBuffer *a3net_ffi_nullable_ptr out);

/**
 * List every user profile. Returns `FfiResult<Vec<UserProfile>>`.
 */
A3netFfiStatus a3net_ffi_user_list_profiles(const char *a3net_ffi_nullable_ptr dataDirPtr,
                                            size_t dataDirLen,
                                            struct A3netFfiBuffer *a3net_ffi_nullable_ptr out);

/**
 * Upsert a user profile. Payload is a JSON `UserProfile`.
 */
A3netFfiStatus a3net_ffi_user_upsert_profile(const char *a3net_ffi_nullable_ptr dataDirPtr,
                                             size_t dataDirLen,
                                             const char *a3net_ffi_nullable_ptr payloadPtr,
                                             size_t payloadLen,
                                             struct A3netFfiBuffer *a3net_ffi_nullable_ptr out);

/**
 * Library version. The C header exposes this as a
 */
uint32_t a3net_ffi_version(void);

#if defined(1)
/**
 * Look up a single bulletin. `payload` is JSON-encoded
 */
A3netFfiStatus a3net_news_get(const char *a3net_ffi_nullable_ptr dataDirPtr,
                              size_t dataDirLen,
                              const char *a3net_ffi_nullable_ptr payloadPtr,
                              size_t payloadLen,
                              struct A3netFfiBuffer *a3net_ffi_nullable_ptr out);
#endif

#if defined(1)
/**
 * Mark a bulletin read. `payload` is JSON-encoded
 */
A3netFfiStatus a3net_news_mark_read(const char *a3net_ffi_nullable_ptr dataDirPtr,
                                    size_t dataDirLen,
                                    const char *a3net_ffi_nullable_ptr payloadPtr,
                                    size_t payloadLen,
                                    struct A3netFfiBuffer *a3net_ffi_nullable_ptr out);
#endif

#if defined(1)
/**
 * Drain buffered events from a subscription. The events are
 */
A3netFfiStatus a3net_news_poll(struct A3netNewsSubHandle *a3net_ffi_nullable_ptr handle,
                               struct A3netFfiBuffer *a3net_ffi_nullable_ptr out);
#endif

#if defined(1)
/**
 * Publish a bulletin. `payload` is JSON-encoded
 */
A3netFfiStatus a3net_news_publish(const char *a3net_ffi_nullable_ptr dataDirPtr,
                                  size_t dataDirLen,
                                  const char *a3net_ffi_nullable_ptr payloadPtr,
                                  size_t payloadLen,
                                  struct A3netFfiBuffer *a3net_ffi_nullable_ptr out);
#endif

#if defined(1)
/**
 * Start a live subscription. Returns a handle via `*out`. The
 */
A3netFfiStatus a3net_news_subscribe(const char *a3net_ffi_nullable_ptr dataDirPtr,
                                    size_t dataDirLen,
                                    const char *a3net_ffi_nullable_ptr payloadPtr,
                                    size_t payloadLen,
                                    struct A3netNewsSubHandle *a3net_ffi_nullable_ptr *a3net_ffi_nullable_ptr out);
#endif

#if defined(1)
/**
 * Fetch a paginated timeline. `payload` is JSON-encoded
 */
A3netFfiStatus a3net_news_timeline(const char *a3net_ffi_nullable_ptr dataDirPtr,
                                   size_t dataDirLen,
                                   const char *a3net_ffi_nullable_ptr payloadPtr,
                                   size_t payloadLen,
                                   struct A3netFfiBuffer *a3net_ffi_nullable_ptr out);
#endif

#if defined(1)
/**
 * Release a subscription handle.
 */
A3netFfiStatus a3net_news_unsubscribe(struct A3netNewsSubHandle *a3net_ffi_nullable_ptr handle);
#endif

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* A3NET_FFI_H */

/* end of cbindgen output */
