//! Typed identifiers used across a3chat.
//!
//! These are thin newtypes over `String` so:
//! - they `Serialize` / `Deserialize` as plain strings,
//! - they implement `Deref<Target = str>` so `&user_id` works in
//!   string contexts,
//! - they implement `Display` for human-readable contexts,
//! - the `validate_id` helper enforces a 1..=128 ASCII charset (same
//!   rules as `a3net_types::invariants::validate_id`).

use serde::{Deserialize, Serialize};

/// User identifier — usually the hex-encoded 32-byte `NodeId` of the
/// user's primary device, or a stable alias chosen by the user.
#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(transparent)]
pub struct UserId(pub String);

/// A single physical device belonging to a user. Multiple devices can
/// share a [`UserId`] (desktop, phone, web).
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct DeviceId(pub String);

/// A 1-to-1 DM (deterministic from sorted user ids) or a group id.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct ConversationId(pub String);

/// Unique message id, generated by the sender.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct MessageId(pub String);

// -- Helpers ---------------------------------------------------------------

/// Validate a string is a non-empty ASCII identifier of bounded length.
/// Returns the inner error type's `InvalidInput` variant on failure so
/// callers can bubble it up.
pub fn validate_id(field: &str, value: &str) -> Result<(), crate::error::A3chatError> {
    use crate::error::A3chatError;
    if value.is_empty() {
        return Err(A3chatError::InvalidInput(format!("{field}: empty")));
    }
    if value.len() > 128 {
        return Err(A3chatError::InvalidInput(format!(
            "{field}: length {} > 128",
            value.len()
        )));
    }
    if !value.is_ascii() {
        return Err(A3chatError::InvalidInput(format!(
            "{field}: non-ASCII characters"
        )));
    }
    // No control characters.
    if value.chars().any(|c| c.is_control()) {
        return Err(A3chatError::InvalidInput(format!(
            "{field}: contains control characters"
        )));
    }
    Ok(())
}

// -- Convenience: deref + display + constructors ----------------------------

macro_rules! impl_string_newtype {
    ($t:ident) => {
        impl $t {
            pub fn new(s: impl Into<String>) -> Self {
                Self(s.into())
            }
            pub fn as_str(&self) -> &str {
                &self.0
            }
            pub fn into_string(self) -> String {
                self.0
            }
        }

        impl std::fmt::Display for $t {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                f.write_str(&self.0)
            }
        }

        impl std::ops::Deref for $t {
            type Target = str;
            fn deref(&self) -> &str {
                &self.0
            }
        }

        impl From<String> for $t {
            fn from(s: String) -> Self {
                Self(s)
            }
        }

        impl From<&str> for $t {
            fn from(s: &str) -> Self {
                Self(s.to_string())
            }
        }

        impl AsRef<str> for $t {
            fn as_ref(&self) -> &str {
                &self.0
            }
        }
    };
}

impl_string_newtype!(UserId);
impl_string_newtype!(DeviceId);
impl_string_newtype!(ConversationId);
impl_string_newtype!(MessageId);

// -- Generators ------------------------------------------------------------

/// Generate a fresh user id — 32 random bytes, hex-encoded (64 chars).
pub fn generate_user_id() -> UserId {
    let bytes: [u8; 32] = rand_bytes();
    UserId(hex::encode(bytes))
}

/// Generate a fresh device id — 16 random bytes, hex-encoded (32 chars).
pub fn generate_device_id() -> DeviceId {
    let bytes: [u8; 16] = rand_bytes();
    DeviceId(hex::encode(bytes))
}

/// Generate a fresh message id — BLAKE3(node_id || nonce || timestamp_ns).
/// 32 bytes, hex-encoded. Collision probability negligible across
/// the lifetime of any single node.
pub fn generate_message_id(node_id: &str) -> MessageId {
    let ts = chrono::Utc::now().timestamp_nanos_opt().unwrap_or(0);
    let mut nonce = [0u8; 16];
    fill_random(&mut nonce);
    let mut h = blake3::Hasher::new();
    h.update(node_id.as_bytes());
    h.update(&ts.to_le_bytes());
    h.update(&nonce);
    MessageId(hex::encode(h.finalize().as_bytes()))
}

/// Generate a deterministic DM conversation id from two user ids.
/// Returns the same id regardless of argument order
/// (`chat_id(a, b) == chat_id(b, a)`) so a node can locally compute
/// the conversation key for any peer without an RPC round-trip.
pub fn generate_conversation_id(user_a: &str, user_b: &str) -> ConversationId {
    let mut ids = [user_a, user_b];
    ids.sort();
    let mut h = blake3::Hasher::new();
    h.update(b"a3chat-dm/v1");
    h.update(ids[0].as_bytes());
    h.update(b"\x00");
    h.update(ids[1].as_bytes());
    ConversationId(format!("dm:{}", hex::encode(h.finalize().as_bytes())))
}

/// Generate a fresh group conversation id (UUID-v4 style — 32 random
/// hex chars prefixed `grp:`).
pub fn generate_group_conversation_id() -> ConversationId {
    let bytes: [u8; 16] = rand_bytes();
    ConversationId(format!("grp:{}", hex::encode(bytes)))
}

/// Inspect the `dm:` / `grp:` prefix on a [`ConversationId`] and report
/// which kind it is. Anything not matching a known prefix is reported
/// as `Other` so callers can fall back gracefully.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ConversationKindHint {
    Dm,
    Group,
    Other,
}

impl ConversationId {
    /// Lightweight kind hint purely from the id prefix — used when we
    /// need to make a routing decision *before* loading the full
    /// [`crate::conversation::ConversationMeta`].
    pub fn kind_hint(&self) -> ConversationKindHint {
        let s = self.as_str();
        if s.starts_with("dm:") {
            ConversationKindHint::Dm
        } else if s.starts_with("grp:") {
            ConversationKindHint::Group
        } else {
            ConversationKindHint::Other
        }
    }
}

// -- Internal helpers ------------------------------------------------------

fn rand_bytes<const N: usize>() -> [u8; N] {
    let mut out = [0u8; N];
    fill_random(&mut out);
    out
}

/// Fill a buffer with random bytes. Uses a thread-local PRNG to avoid
/// pulling in `rand` as a hard dependency; the quality is fine for
/// id generation (cryptographic keys come from `a3chat-crypto`).
fn fill_random(buf: &mut [u8]) {
    use std::cell::RefCell;
    use std::collections::hash_map::DefaultHasher;
    use std::hash::{Hash, Hasher};
    use std::time::{SystemTime, UNIX_EPOCH};

    thread_local! {
        static SEED: RefCell<u64> = RefCell::new({
            let nanos = SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .map(|d| d.as_nanos() as u64)
                .unwrap_or(0xA5A5_A5A5_A5A5_A5A5);
            let mut h = DefaultHasher::new();
            nanos.hash(&mut h);
            h.finish() ^ 0xDEAD_BEEF_CAFE_BABE
        });
    }

    SEED.with(|cell| {
        let mut state = cell.borrow_mut();
        for chunk in buf.chunks_mut(8) {
            // SplitMix64 step — fast, decent avalanche for id-gen.
            // Source: https://prng.di.unimi.it/splitmix64.c (public domain).
            let mut z = *state ^ 0x9E37_79B9_7F4A_7C15;
            z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
            z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
            *state = z ^ (z >> 31);
            let bytes = z.to_le_bytes();
            for (i, slot) in chunk.iter_mut().enumerate() {
                *slot = bytes[i];
            }
        }
    });
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn dm_id_is_symmetric() {
        let a = generate_conversation_id("alice", "bob");
        let b = generate_conversation_id("bob", "alice");
        assert_eq!(a, b);
        let c = generate_conversation_id("alice", "eve");
        assert_ne!(a, c);
        assert!(a.as_str().starts_with("dm:"));
    }

    #[test]
    fn user_id_is_hex64() {
        let u = generate_user_id();
        assert_eq!(u.as_str().len(), 64);
        assert!(u.as_str().chars().all(|c| c.is_ascii_hexdigit()));
    }

    #[test]
    fn device_id_is_hex32() {
        let d = generate_device_id();
        assert_eq!(d.as_str().len(), 32);
    }

    #[test]
    fn message_id_is_unique_per_node() {
        let m1 = generate_message_id("node-a");
        let m2 = generate_message_id("node-a");
        // Not strictly unique in a fast loop (same nanosecond), but
        // extremely unlikely — we just check it's well-formed.
        assert_eq!(m1.as_str().len(), 64);
        assert!(m1.as_str().chars().all(|c| c.is_ascii_hexdigit()));
        assert_ne!(m1, m2, "nonces must differ");
    }

    #[test]
    fn message_id_differs_across_nodes() {
        let m1 = generate_message_id("node-a");
        let m2 = generate_message_id("node-b");
        assert_ne!(m1, m2, "different node ids yield different message ids");
    }

    #[test]
    fn validate_id_accepts_and_rejects() {
        assert!(validate_id("u", "alice").is_ok());
        assert!(validate_id("u", "").is_err());
        assert!(validate_id("u", &"x".repeat(129)).is_err());
        assert!(validate_id("u", "alice\u{1F600}").is_err()); // non-ASCII
        assert!(validate_id("u", "alice\n").is_err()); // control char
    }

    #[test]
    fn newtype_deref_and_display() {
        let u = UserId::new("alice");
        assert_eq!(u.as_str(), "alice");
        assert_eq!(format!("{u}"), "alice");
        assert_eq!(&*u, "alice");
        let u2: UserId = "alice".into();
        assert_eq!(u, u2);
        let u3: UserId = String::from("alice").into();
        assert_eq!(u, u3);
    }
}
