//! JSON Schema export — a hand-written, minimal schema description
//! of every public a3chat-core type.
//!
//! We deliberately do **not** pull in `schemars` (which depends on
//! `serde_json` + a non-trivial proc-macro pipeline). The schema
//! below is generated by hand from the type definitions and serves
//! as a stable contract that frontends (TypeScript, Dart, Swift) can
//! consume via quicktype or similar.
//!
//! `a3chat-cli` can dump the schema to stdout for codegen.
//!
//! ```text
//! $ cargo run -p a3chat-cli -- schema > schema.json
//! ```
//!
//! Note on construction style: we build every `Value` iteratively
//! (helpers below) and never use `serde_json::json!{}`. The
//! `json!{}` macro expands recursively — one stack frame per
//! nested literal — and our schema is deep enough (multi-level
//! `properties` + `oneOf` + `items` with `$ref`) to exceed
//! rustc's default 128-frame macro recursion limit. The iterative
//! form scales linearly with the document size and has no macro
//! recursion at all.

use serde_json::{Map, Value, json};

/// Convenience constructor for a JSON object value.
fn obj<I>(entries: I) -> Value
where
    I: IntoIterator<Item = (String, Value)>,
{
    let mut m = Map::new();
    for (k, v) in entries {
        m.insert(k, v);
    }
    Value::Object(m)
}

/// Convenience constructor for a JSON array value.
fn arr<I>(items: I) -> Value
where
    I: IntoIterator<Item = Value>,
{
    Value::Array(items.into_iter().collect())
}

/// `$ref` to a definition.
fn def(name: &str) -> Value {
    json!(format!("#/definitions/{name}"))
}

/// Shorthand: object with a single `type` constraint.
fn ty(t: &str) -> Value {
    obj([("type".to_string(), json!(t))])
}

/// Shorthand: a `$ref` to a definition.
fn ref_to(name: &str) -> Value {
    def(name)
}

/// `oneOf: [{...}, {"type": "null"}]` — "T or null".
fn nullable(inner: Value) -> Value {
    arr([inner, obj([("type".to_string(), json!("null"))])])
}

/// Identifier-string constraints (printable ASCII, length-bounded).
fn id_string(min: usize, max: usize) -> Value {
    obj([
        ("type".to_string(), json!("string")),
        ("minLength".to_string(), json!(min)),
        ("maxLength".to_string(), json!(max)),
        (
            "pattern".to_string(),
            json!(r#"^[\x20-\x7E]+$"#),
        ),
    ])
}

/// A 64-char lowercase / uppercase hex string — e.g. SHA-256 hashes.
fn hex_hash() -> Value {
    obj([
        ("type".to_string(), json!("string")),
        ("minLength".to_string(), json!(64)),
        ("maxLength".to_string(), json!(64)),
        (
            "pattern".to_string(),
            json!("^[0-9a-fA-F]{64}$"),
        ),
    ])
}

/// A 24-char hex string — e.g. AEAD nonce.
fn hex_nonce() -> Value {
    obj([
        ("type".to_string(), json!("string")),
        ("minLength".to_string(), json!(24)),
        ("maxLength".to_string(), json!(24)),
        (
            "pattern".to_string(),
            json!("^[0-9a-fA-F]{24}$"),
        ),
    ])
}

/// A 32-char hex string — e.g. AEAD authentication tag.
fn hex_tag() -> Value {
    obj([
        ("type".to_string(), json!("string")),
        ("minLength".to_string(), json!(32)),
        ("maxLength".to_string(), json!(32)),
        (
            "pattern".to_string(),
            json!("^[0-9a-fA-F]{32}$"),
        ),
    ])
}

/// A length-bounded string with no other constraints.
fn bounded_string(min: usize, max: usize) -> Value {
    obj([
        ("type".to_string(), json!("string")),
        ("minLength".to_string(), json!(min)),
        ("maxLength".to_string(), json!(max)),
    ])
}

/// A string with only an upper-bound length constraint.
fn max_len_string(max: usize) -> Value {
    obj([
        ("type".to_string(), json!("string")),
        ("maxLength".to_string(), json!(max)),
    ])
}

/// A string with only a lower-bound length constraint.
fn min_len_string(min: usize) -> Value {
    obj([
        ("type".to_string(), json!("string")),
        ("minLength".to_string(), json!(min)),
    ])
}

/// Optional version of [`max_len_string`].
fn optional_max_len_string(max: usize) -> Value {
    nullable(max_len_string(max))
}

/// A length-bounded optional string.
fn optional_bounded_string(min: usize, max: usize) -> Value {
    nullable(bounded_string(min, max))
}

/// A `date-time` formatted string (RFC3339).
fn date_time() -> Value {
    obj([
        ("type".to_string(), json!("string")),
        ("format".to_string(), json!("date-time")),
    ])
}

fn optional_date_time() -> Value {
    nullable(date_time())
}

/// A URI formatted string.
fn uri() -> Value {
    obj([
        ("type".to_string(), json!("string")),
        ("format".to_string(), json!("uri")),
    ])
}

fn optional_uri() -> Value {
    nullable(uri())
}

/// A 64-char printable string used for public-key fields.
fn public_key() -> Value {
    bounded_string(64, 64)
}

fn optional_public_key() -> Value {
    nullable(public_key())
}

/// `MessageBody` — either a plain UTF-8 body or an encrypted envelope.
fn schema_message_body() -> Value {
    let plain = obj([
        (
            "type".to_string(),
            json!("object"),
        ),
        (
            "additionalProperties".to_string(),
            json!(false),
        ),
        (
            "required".to_string(),
            arr([json!("kind"), json!("content")]),
        ),
        (
            "properties".to_string(),
            obj([
                ("kind".to_string(), obj([("const".to_string(), json!("plain"))])),
                (
                    "content".to_string(),
                    bounded_string(1, 16384),
                ),
            ]),
        ),
    ]);

    let encrypted = obj([
        ("type".to_string(), json!("object")),
        (
            "additionalProperties".to_string(),
            json!(false),
        ),
        (
            "required".to_string(),
            arr([
                json!("kind"),
                json!("algorithm"),
                json!("nonce"),
                json!("ciphertext"),
                json!("tag"),
            ]),
        ),
        (
            "properties".to_string(),
            obj([
                (
                    "kind".to_string(),
                    obj([("const".to_string(), json!("encrypted"))]),
                ),
                (
                    "algorithm".to_string(),
                    max_len_string(64),
                ),
                ("nonce".to_string(), hex_nonce()),
                (
                    "ciphertext".to_string(),
                    min_len_string(1),
                ),
                ("tag".to_string(), hex_tag()),
            ]),
        ),
    ]);

    obj([("oneOf".to_string(), arr([plain, encrypted]))])
}

/// Build the `Attachment` schema.
fn schema_attachment() -> Value {
    obj([
        ("type".to_string(), json!("object")),
        (
            "additionalProperties".to_string(),
            json!(false),
        ),
        (
            "required".to_string(),
            arr([
                json!("attachment_id"),
                json!("file_type"),
                json!("blob_hash"),
                json!("file_name"),
                json!("file_size"),
            ]),
        ),
        (
            "properties".to_string(),
            obj([
                (
                    "attachment_id".to_string(),
                    bounded_string(1, 128),
                ),
                ("file_type".to_string(), ref_to("AttachmentKind")),
                ("blob_hash".to_string(), hex_hash()),
                (
                    "file_name".to_string(),
                    bounded_string(1, 256),
                ),
                (
                    "file_size".to_string(),
                    obj([
                        ("type".to_string(), json!("integer")),
                        ("minimum".to_string(), json!(0)),
                    ]),
                ),
                (
                    "thumbnail_hash".to_string(),
                    nullable(hex_hash()),
                ),
            ]),
        ),
    ])
}

/// Build the `ChatMessage` schema.
fn schema_chat_message() -> Value {
    obj([
        ("type".to_string(), json!("object")),
        (
            "additionalProperties".to_string(),
            json!(false),
        ),
        (
            "required".to_string(),
            arr([
                json!("message_id"),
                json!("conversation_id"),
                json!("sender_id"),
                json!("receiver_id"),
                json!("message_type"),
                json!("body"),
                json!("attachments"),
                json!("sequence"),
                json!("timestamp"),
                json!("is_edited"),
            ]),
        ),
        (
            "properties".to_string(),
            obj([
                ("message_id".to_string(), ref_to("MessageId")),
                ("conversation_id".to_string(), ref_to("ConversationId")),
                ("sender_id".to_string(), ref_to("UserId")),
                ("receiver_id".to_string(), ref_to("UserId")),
                ("message_type".to_string(), ref_to("MessageType")),
                ("body".to_string(), ref_to("MessageBody")),
                (
                    "attachments".to_string(),
                    obj([
                        ("type".to_string(), json!("array")),
                        ("maxItems".to_string(), json!(32)),
                        ("items".to_string(), ref_to("Attachment")),
                    ]),
                ),
                (
                    "reply_to".to_string(),
                    nullable(ref_to("MessageId")),
                ),
                (
                    "sequence".to_string(),
                    obj([
                        ("type".to_string(), json!("integer")),
                        ("minimum".to_string(), json!(0)),
                        ("maximum".to_string(), json!(9999)),
                    ]),
                ),
                (
                    "timestamp".to_string(),
                    obj([
                        ("type".to_string(), json!("integer")),
                        ("minimum".to_string(), json!(0)),
                    ]),
                ),
                ("read_at".to_string(), optional_date_time()),
                ("is_edited".to_string(), ty("boolean")),
                ("edited_at".to_string(), optional_date_time()),
                ("integrity_hash".to_string(), nullable(ty("string"))),
                ("recalled_at".to_string(), optional_date_time()),
            ]),
        ),
    ])
}

/// Build the `MessageEnvelope` schema (the wire shape a client sends).
fn schema_message_envelope() -> Value {
    obj([
        ("type".to_string(), json!("object")),
        (
            "additionalProperties".to_string(),
            json!(false),
        ),
        (
            "required".to_string(),
            arr([
                json!("conversation_id"),
                json!("receiver_id"),
                json!("message_type"),
                json!("body"),
                json!("attachments"),
                json!("sequence"),
                json!("timestamp"),
            ]),
        ),
        (
            "properties".to_string(),
            obj([
                ("conversation_id".to_string(), ref_to("ConversationId")),
                ("receiver_id".to_string(), ref_to("UserId")),
                ("message_type".to_string(), ref_to("MessageType")),
                ("body".to_string(), ref_to("MessageBody")),
                (
                    "attachments".to_string(),
                    obj([
                        ("type".to_string(), json!("array")),
                        ("maxItems".to_string(), json!(32)),
                        ("items".to_string(), ref_to("Attachment")),
                    ]),
                ),
                (
                    "reply_to".to_string(),
                    nullable(ref_to("MessageId")),
                ),
                (
                    "sequence".to_string(),
                    obj([
                        ("type".to_string(), json!("integer")),
                        ("minimum".to_string(), json!(0)),
                        ("maximum".to_string(), json!(9999)),
                    ]),
                ),
                (
                    "timestamp".to_string(),
                    obj([
                        ("type".to_string(), json!("integer")),
                        ("minimum".to_string(), json!(0)),
                    ]),
                ),
            ]),
        ),
    ])
}

/// Build the `Contact` schema.
fn schema_contact() -> Value {
    obj([
        ("type".to_string(), json!("object")),
        (
            "additionalProperties".to_string(),
            json!(false),
        ),
        (
            "required".to_string(),
            arr([
                json!("user_id"),
                json!("display_name"),
                json!("is_favorite"),
                json!("is_blocked"),
                json!("added_at"),
            ]),
        ),
        (
            "properties".to_string(),
            obj([
                ("user_id".to_string(), ref_to("UserId")),
                ("display_name".to_string(), bounded_string(1, 256)),
                ("avatar_url".to_string(), optional_uri()),
                ("note".to_string(), max_len_string(1024)),
                ("is_favorite".to_string(), ty("boolean")),
                ("is_blocked".to_string(), ty("boolean")),
                ("added_at".to_string(), date_time()),
                (
                    "last_interaction_at".to_string(),
                    optional_date_time(),
                ),
                ("public_key".to_string(), optional_public_key()),
            ]),
        ),
    ])
}

/// Build the `Group` schema.
fn schema_group() -> Value {
    obj([
        ("type".to_string(), json!("object")),
        (
            "additionalProperties".to_string(),
            json!(false),
        ),
        (
            "required".to_string(),
            arr([
                json!("conversation_id"),
                json!("name"),
                json!("owner_id"),
                json!("member_count"),
                json!("created_at"),
                json!("last_activity"),
                json!("is_private"),
                json!("is_dissolved"),
            ]),
        ),
        (
            "properties".to_string(),
            obj([
                ("conversation_id".to_string(), ref_to("ConversationId")),
                ("name".to_string(), bounded_string(1, 256)),
                ("description".to_string(), max_len_string(1024)),
                ("avatar_url".to_string(), optional_uri()),
                ("owner_id".to_string(), ref_to("UserId")),
                (
                    "member_count".to_string(),
                    obj([
                        ("type".to_string(), json!("integer")),
                        ("minimum".to_string(), json!(0)),
                        ("maximum".to_string(), json!(500)),
                    ]),
                ),
                ("created_at".to_string(), date_time()),
                ("last_activity".to_string(), date_time()),
                (
                    "last_sequence".to_string(),
                    obj([
                        ("type".to_string(), json!("integer")),
                        ("minimum".to_string(), json!(0)),
                        ("maximum".to_string(), json!(9999)),
                    ]),
                ),
                ("is_private".to_string(), ty("boolean")),
                ("is_dissolved".to_string(), ty("boolean")),
            ]),
        ),
    ])
}

/// Build the `GroupMember` schema.
fn schema_group_member() -> Value {
    obj([
        ("type".to_string(), json!("object")),
        (
            "additionalProperties".to_string(),
            json!(false),
        ),
        (
            "required".to_string(),
            arr([
                json!("user_id"),
                json!("display_name"),
                json!("role"),
                json!("joined_at"),
                json!("is_online"),
            ]),
        ),
        (
            "properties".to_string(),
            obj([
                ("user_id".to_string(), ref_to("UserId")),
                ("display_name".to_string(), bounded_string(1, 256)),
                ("role".to_string(), ref_to("MemberRole")),
                ("joined_at".to_string(), date_time()),
                ("last_seen".to_string(), optional_date_time()),
                ("is_online".to_string(), ty("boolean")),
                (
                    "nickname".to_string(),
                    optional_bounded_string(1, 256),
                ),
            ]),
        ),
    ])
}

/// Build the `ConversationMeta` schema.
fn schema_conversation_meta() -> Value {
    obj([
        ("type".to_string(), json!("object")),
        (
            "additionalProperties".to_string(),
            json!(false),
        ),
        (
            "required".to_string(),
            arr([
                json!("conversation_id"),
                json!("kind"),
                json!("title"),
                json!("last_message_preview"),
                json!("last_activity"),
                json!("message_count"),
                json!("unread_count"),
                json!("peer_online"),
                json!("muted"),
                json!("pinned"),
            ]),
        ),
        (
            "properties".to_string(),
            obj([
                ("conversation_id".to_string(), ref_to("ConversationId")),
                ("kind".to_string(), ref_to("ConversationKind")),
                ("title".to_string(), bounded_string(1, 256)),
                (
                    "peer_user_id".to_string(),
                    nullable(ref_to("UserId")),
                ),
                (
                    "last_message_preview".to_string(),
                    max_len_string(256),
                ),
                (
                    "last_activity".to_string(),
                    obj([
                        ("type".to_string(), json!("integer")),
                        ("minimum".to_string(), json!(0)),
                    ]),
                ),
                (
                    "message_count".to_string(),
                    obj([
                        ("type".to_string(), json!("integer")),
                        ("minimum".to_string(), json!(0)),
                    ]),
                ),
                (
                    "unread_count".to_string(),
                    obj([
                        ("type".to_string(), json!("integer")),
                        ("minimum".to_string(), json!(0)),
                    ]),
                ),
                ("peer_online".to_string(), ty("boolean")),
                ("muted".to_string(), ty("boolean")),
                ("pinned".to_string(), ty("boolean")),
            ]),
        ),
    ])
}

/// Build the `Presence` schema.
fn schema_presence() -> Value {
    obj([
        ("type".to_string(), json!("object")),
        (
            "additionalProperties".to_string(),
            json!(false),
        ),
        (
            "required".to_string(),
            arr([
                json!("user_id"),
                json!("status"),
                json!("last_changed"),
            ]),
        ),
        (
            "properties".to_string(),
            obj([
                ("user_id".to_string(), ref_to("UserId")),
                ("status".to_string(), ref_to("PresenceStatus")),
                (
                    "status_message".to_string(),
                    optional_max_len_string(256),
                ),
                ("last_changed".to_string(), date_time()),
            ]),
        ),
    ])
}

/// Build the `A3chatNotification` schema.
fn schema_a3chat_notification() -> Value {
    obj([
        ("type".to_string(), json!("object")),
        (
            "additionalProperties".to_string(),
            json!(false),
        ),
        (
            "required".to_string(),
            arr([json!("kind"), json!("payload"), json!("timestamp")]),
        ),
        (
            "properties".to_string(),
            obj([
                ("kind".to_string(), ty("string")),
                ("payload".to_string(), ty("object")),
                ("timestamp".to_string(), date_time()),
            ]),
        ),
    ])
}

/// Helper that adds a definition only if absent — guards against
/// duplicate-name bugs during refactors.
fn add_def(map: &mut Map<String, Value>, name: &str, value: Value) {
    map.insert(name.to_string(), value);
}

/// Return the entire a3chat-core JSON Schema document.
///
/// Currently `$defs` is empty and each top-level type is rendered as
/// a `oneOf` over its variants. Future versions may switch to
/// `definitions` with `$ref` indirection once quicktype handles them.
pub fn a3chat_json_schema() -> Value {
    let mut definitions = Map::new();

    // -- Identifier strings ------------------------------------------------
    add_def(&mut definitions, "UserId", id_string(1, 128));
    add_def(&mut definitions, "DeviceId", id_string(1, 128));
    add_def(
        &mut definitions,
        "ConversationId",
        bounded_string(1, 128),
    );
    add_def(&mut definitions, "MessageId", hex_hash());

    // -- Enums -------------------------------------------------------------
    add_def(
        &mut definitions,
        "ConversationKind",
        obj([
            ("type".to_string(), json!("string")),
            (
                "enum".to_string(),
                arr([json!("dm"), json!("group")]),
            ),
        ]),
    );
    add_def(
        &mut definitions,
        "MessageType",
        obj([
            ("type".to_string(), json!("string")),
            (
                "enum".to_string(),
                arr([
                    json!("text"),
                    json!("image"),
                    json!("file"),
                    json!("voice"),
                    json!("video"),
                    json!("system"),
                    json!("call"),
                ]),
            ),
        ]),
    );
    add_def(
        &mut definitions,
        "AttachmentKind",
        obj([
            ("type".to_string(), json!("string")),
            (
                "enum".to_string(),
                arr([
                    json!("image"),
                    json!("audio"),
                    json!("video"),
                    json!("file"),
                ]),
            ),
        ]),
    );
    add_def(
        &mut definitions,
        "MemberRole",
        obj([
            ("type".to_string(), json!("string")),
            (
                "enum".to_string(),
                arr([json!("owner"), json!("admin"), json!("member")]),
            ),
        ]),
    );
    add_def(
        &mut definitions,
        "ContactRequestStatus",
        obj([
            ("type".to_string(), json!("string")),
            (
                "enum".to_string(),
                arr([
                    json!("pending"),
                    json!("accepted"),
                    json!("rejected"),
                    json!("expired"),
                    json!("cancelled"),
                ]),
            ),
        ]),
    );
    add_def(
        &mut definitions,
        "InvitationStatus",
        obj([
            ("type".to_string(), json!("string")),
            (
                "enum".to_string(),
                arr([
                    json!("pending"),
                    json!("accepted"),
                    json!("rejected"),
                    json!("expired"),
                    json!("cancelled"),
                ]),
            ),
        ]),
    );
    add_def(
        &mut definitions,
        "PresenceStatus",
        obj([
            ("type".to_string(), json!("string")),
            (
                "enum".to_string(),
                arr([
                    json!("online"),
                    json!("away"),
                    json!("offline"),
                    json!("invisible"),
                ]),
            ),
        ]),
    );

    // -- Composite schemas -------------------------------------------------
    add_def(&mut definitions, "MessageBody", schema_message_body());
    add_def(&mut definitions, "Attachment", schema_attachment());
    add_def(&mut definitions, "ChatMessage", schema_chat_message());
    add_def(
        &mut definitions,
        "MessageEnvelope",
        schema_message_envelope(),
    );
    add_def(&mut definitions, "Contact", schema_contact());
    add_def(&mut definitions, "Group", schema_group());
    add_def(&mut definitions, "GroupMember", schema_group_member());
    add_def(
        &mut definitions,
        "ConversationMeta",
        schema_conversation_meta(),
    );
    add_def(&mut definitions, "Presence", schema_presence());
    add_def(
        &mut definitions,
        "A3chatNotification",
        schema_a3chat_notification(),
    );

    // -- Compose final document -------------------------------------------
    let mut root = Map::new();
    root.insert(
        "$schema".to_string(),
        json!("https://json-schema.org/draft/2020-12/schema"),
    );
    root.insert(
        "$id".to_string(),
        json!("https://github.com/arksong/a3net/a3chat-core/schema.json"),
    );
    root.insert("title".to_string(), json!("a3chat-core"));
    root.insert(
        "description".to_string(),
        json!(
            "Domain types shared by a3chat server, Tauri desktop, and Flutter mobile clients."
        ),
    );
    root.insert("version".to_string(), json!(env!("CARGO_PKG_VERSION")));
    root.insert("definitions".to_string(), Value::Object(definitions));
    Value::Object(root)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn schema_is_valid_json_object() {
        let s = a3chat_json_schema();
        assert!(s.is_object());
        assert_eq!(s["$schema"], "https://json-schema.org/draft/2020-12/schema");
        assert!(s["definitions"].is_object());
    }

    #[test]
    fn schema_contains_core_types() {
        let s = a3chat_json_schema();
        let defs = s["definitions"].as_object().expect("definitions is object");
        for expected in [
            "UserId",
            "ConversationId",
            "MessageId",
            "ChatMessage",
            "MessageBody",
            "Contact",
            "Group",
            "GroupMember",
            "ConversationMeta",
            "A3chatNotification",
        ] {
            assert!(
                defs.contains_key(expected),
                "schema missing definition for {expected}"
            );
        }
    }

    #[test]
    fn schema_can_be_serialized_round_trip() {
        let s = a3chat_json_schema();
        let ser = serde_json::to_string(&s).expect("serialize schema");
        let de: Value = serde_json::from_str(&ser).expect("parse schema");
        assert_eq!(de, s);
    }
}
