//! Property-based tests for the social feed.
//!
//! The goal: ensure the typed records' invariants hold for
//! arbitrary shapes generated by `proptest`, and that the
//! `validate()` gates genuinely reject the malformed shapes
//! rather than letting them slip through.

use adnet_socialfeed::SocialFeedService;
use adnet_types::invariants::{
    AttachmentKind, ReactionTarget, ReactionType, Visibility,
};
use adnet_types::social_feed::{PostAttachment, SocialPost, SocialReaction};
use adnet_types::ContentHash;
use proptest::prelude::*;
use tempfile::TempDir;

fn sample() -> SocialPost {
    SocialPost {
        post_id: "p-prop".into(),
        author_id: "alice".into(),
        author_name: "Alice".into(),
        author_avatar: None,
        content: "hi".into(),
        attachments: vec![],
        tags: vec![],
        visibility: Visibility::Public,
        location: None,
        mentions: vec![],
        created_at: 1,
        updated_at: 1,
        like_count: 0,
        comment_count: 0,
        share_count: 0,
        public_account_id: None,
        integrity_hash: None,
        sequence: 1,
        is_edited: false,
        edited_at: None,
    }
}

fn attachment_blob() -> String {
    ContentHash::from_bytes(b"abc").as_hex().to_string()
}

proptest! {
    /// Any sequence of valid `[a-z0-9 ]` content passes validation;
    /// empty content fails. Pure round-trip invariant.
    #[test]
    fn prop_post_validates_or_rejects(content in "[a-z0-9 ]{0,128}") {
        let mut p = sample();
        p.content = content.clone();
        let ok = content.len() >= 1
            && content.len() <= adnet_types::invariants::MAX_CONTENT_LEN;
        assert_eq!(p.validate().is_ok(), ok);
    }

    /// Attachments with non-hex blob hashes are rejected.
    #[test]
    fn prop_attachment_blob_hash_validation(blob in "[a-z0-9]{0,128}") {
        let a = PostAttachment {
            attachment_id: "a1".into(),
            attachment_type: AttachmentKind::Image,
            blob_hash: blob.clone(),
            file_name: "x.png".into(),
            file_size: 100,
            thumbnail_hash: None,
            caption: None,
        };
        let blob_len = blob.len();
        let ok = blob_len == ContentHash::HEX_LEN
            && blob.chars().all(|c| c.is_ascii_hexdigit());
        assert_eq!(a.validate().is_ok(), ok, "blob_len={blob_len} blob={blob:?}");
    }

    /// Reactions with empty id/target/user are rejected; valid
    /// shapes pass.
    #[test]
    fn prop_reaction_validates(
        id in "[a-zA-Z0-9-]{0,16}",
        target in "[a-zA-Z0-9-]{0,16}",
        user in "[a-zA-Z0-9-]{0,16}",
    ) {
        let r = SocialReaction {
            reaction_id: id.clone(),
            target_id: target.clone(),
            target_type: ReactionTarget::Post,
            user_id: user.clone(),
            reaction_type: ReactionType::Like,
            created_at: 1,
        };
        let ok = !id.is_empty() && !target.is_empty() && !user.is_empty();
        assert_eq!(r.validate().is_ok(), ok, "ids: {id:?} {target:?} {user:?}");
    }
}

#[tokio::test]
async fn service_rejects_invalid_posts_at_boundary() {
    let dir = TempDir::new().unwrap();
    let svc = SocialFeedService::new(adnet_socialfeed::SocialFeedServiceConfig {
        storage: adnet_socialfeed::SocialFeedStorageConfig {
            storage_dir: dir.path().to_path_buf(),
            filename: "p.db".into(),
        },
        gossip: None,
        local_node: Some(adnet_types::NodeId::random()),
        validation_policy: adnet_ipc::validation::ValidationPolicy::Strict,
        gossip_transport: None,
    })
    .unwrap();
    let mut p = sample();
    p.content = "".into();
    let res = svc.create_post(p).await;
    assert!(res.is_err());

    // Sanity: valid posts still work.
    let stored = svc.create_post(sample()).await.unwrap();
    assert!(!stored.post_id.is_empty());
}

#[tokio::test]
async fn attachment_blob_hash_roundtrips() {
    let dir = TempDir::new().unwrap();
    let svc = SocialFeedService::new(adnet_socialfeed::SocialFeedServiceConfig {
        storage: adnet_socialfeed::SocialFeedStorageConfig {
            storage_dir: dir.path().to_path_buf(),
            filename: "att.db".into(),
        },
        gossip: None,
        local_node: Some(adnet_types::NodeId::random()),
        validation_policy: adnet_ipc::validation::ValidationPolicy::Strict,
        gossip_transport: None,
    })
    .unwrap();
    let mut p = sample();
    p.attachments.push(PostAttachment {
        attachment_id: "a1".into(),
        attachment_type: AttachmentKind::Image,
        blob_hash: attachment_blob(),
        file_name: "x.png".into(),
        file_size: 100,
        thumbnail_hash: None,
        caption: None,
    });
    let stored = svc.create_post(p).await.unwrap();
    let fetched = svc.get_post(&stored.post_id).unwrap().unwrap();
    assert_eq!(fetched.attachments.len(), 1);
    assert_eq!(fetched.attachments[0].blob_hash, attachment_blob());
}
