//! Mesh-to-mesh peering grants (RFC-0007).
//!
//! A peering grant is a signed envelope that authorises
//! members of one mesh (the *source*) to transit through
//! nodes of another mesh (the *target*). The grant is
//! published on the *source* mesh's gossip topic so any
//! potential transit node that subscribes to it can apply
//! the grant to its routing decision.
//!
//! This module is **pure data + access trait**. It does
//! not perform the actual signing — the coordinator owns
//! the wire format, the `adnet-identity` crate (or its
//! successor) owns the cryptographic primitive. The
//! `signature` field is a hex string, matching the
//! convention already used by [`MeshMembership`].
//!
//! ## Lifecycle
//!
//! ```text
//!   1. mesh B coordinator: create grant(source=A, target=B, ttl=24h)
//!      → returns a `PeeringGrant` with empty signature.
//!
//!   2. mesh B coordinator: sign the grant envelope
//!      with the B coordinator's key (caller's job —
//!      identity crate).
//!
//!   3. publish the signed envelope on mesh B's gossip
//!      topic `adnet-transit/v1`.
//!
//!   4. peers of mesh B apply the grant to their
//!      `TransitTopology` → `GossipFederatedTopology::observe_grant`.
//!
//!   5. revocation: publish a `PeeringRevocation` carrying
//!      the same `grant_id`; `GossipFederatedTopology` prunes
//!      the grant on sight.
//! ```

use std::collections::HashMap;
use std::sync::Arc;
use std::time::Duration;

use chrono::{DateTime, Utc};
use parking_lot::RwLock;
use serde::{Deserialize, Serialize};

use adnet_types::{MeshNetworkId, NodeId};

use crate::error::{CoordinatorError, CoordinatorResult};

/// Maximum TTL for a peering grant (30 days). The cap is
/// deliberately lower than the invite-code cap (7 days) —
/// peerings are a higher-trust relationship and we want
/// operators to renew them regularly.
pub const MAX_PEERING_TTL: Duration = Duration::from_secs(30 * 24 * 3600);

/// Stable identifier for a peering grant. Generated by the
/// grantor (source mesh coordinator); unique within the
/// source mesh. The pair `(source_network, grant_id)`
/// identifies a grant globally.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct PeeringGrantId(pub String);

impl PeeringGrantId {
    pub fn new() -> Self {
        Self(uuid::Uuid::new_v4().to_string())
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl Default for PeeringGrantId {
    fn default() -> Self {
        Self::new()
    }
}

impl std::fmt::Display for PeeringGrantId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.0)
    }
}

/// Direction of a peering grant.
///
/// The default is `Bidirectional` — both meshes can
/// transit through each other. For tighter scoping,
/// `SourceCanTransitThroughTarget` says "members of
/// `source` may transit through `target`, but not the
/// other way around".
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PeeringDirection {
    /// Both directions permitted.
    #[default]
    Bidirectional,
    /// Only source→target permitted.
    SourceToTarget,
}

impl PeeringDirection {
    /// Whether `source_to_target` (i.e. transit from
    /// `source` to `target`) is permitted by this grant.
    pub fn allows(self, source_to_target: bool) -> bool {
        match self {
            Self::Bidirectional => true,
            Self::SourceToTarget => source_to_target,
        }
    }
}

/// A signed envelope authorising members of `source` to
/// transit through nodes of `target`.
///
/// The `signature` field is left empty by the coordinator
/// and is expected to be filled in by the signing layer
/// (the same way `MeshMembership.signature` is). The
/// canonical signing preimage is
/// [`PeeringGrant::signing_preimage`] — a BLAKE3 hash of
/// the canonical JSON of the unsigned fields.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PeeringGrant {
    /// Unique id within the source mesh.
    pub grant_id: PeeringGrantId,
    /// The mesh whose members are granted transit.
    pub source: MeshNetworkId,
    /// The mesh whose transit nodes will accept the
    /// forwarded traffic.
    pub target: MeshNetworkId,
    /// The granting coordinator's node id. Verifiers
    /// check that the recovered pubkey matches
    /// `source`'s coordinator key.
    pub grantor: NodeId,
    /// Direction of the grant.
    #[serde(default)]
    pub direction: PeeringDirection,
    /// Route-metric hint for the cheapest path through
    /// this peering. Default `1` (direct). Operators can
    /// raise it to demote a flaky link.
    #[serde(default = "default_cost")]
    pub cost: u8,
    /// When the grant expires.
    pub valid_until: DateTime<Utc>,
    /// When the grant was created.
    pub created_at: DateTime<Utc>,
    /// Hex-encoded signature over `signing_preimage`.
    /// Empty until the caller signs the envelope.
    #[serde(default)]
    pub signature: String,
}

fn default_cost() -> u8 {
    1
}

impl PeeringGrant {
    /// Build an unsigned grant. `signature` is left empty.
    pub fn new_unsigned(
        source: MeshNetworkId,
        target: MeshNetworkId,
        grantor: NodeId,
        ttl: Duration,
    ) -> CoordinatorResult<Self> {
        if source == target {
            return Err(CoordinatorError::PeeringSelfLoop);
        }
        let ttl = ttl.min(MAX_PEERING_TTL);
        let now = Utc::now();
        Ok(Self {
            grant_id: PeeringGrantId::new(),
            source,
            target,
            grantor,
            direction: PeeringDirection::default(),
            cost: default_cost(),
            valid_until: now + chrono::Duration::from_std(ttl).unwrap_or(chrono::Duration::days(30)),
            created_at: now,
            signature: String::new(),
        })
    }

    /// Canonical signing preimage. The signature is
    /// computed over BLAKE3 of this blob.
    pub fn signing_preimage(&self) -> Vec<u8> {
        // Canonicalise: serialize the unsigned fields in
        // a deterministic order. We deliberately exclude
        // `signature` and `created_at` so the signature
        // is reproducible across "re-publish" events.
        //
        // Use serde_json with sorted keys to make the
        // order stable on the wire. The helpers below
        // produce a struct that is structurally identical
        // to `(grant_id, source, target, grantor,
        // direction, cost, valid_until)`.
        let canonical = CanonicalPeeringGrant {
            grant_id: &self.grant_id,
            source: &self.source,
            target: &self.target,
            grantor: &self.grantor,
            direction: self.direction,
            cost: self.cost,
            valid_until: self.valid_until,
        };
        let mut buf = serde_json::to_vec(&canonical)
            .expect("PeeringGrant canonical serialisation is infallible");
        // Append a single NUL as a domain separator so
        // this blob can never collide with another JSON
        // payload that happens to be byte-identical.
        buf.push(0);
        buf
    }

    /// BLAKE3 digest of the signing preimage.
    pub fn signing_digest(&self) -> [u8; 32] {
        let mut h = blake3::Hasher::new();
        h.update(&self.signing_preimage());
        let out = h.finalize();
        let mut digest = [0u8; 32];
        digest.copy_from_slice(out.as_bytes());
        digest
    }

    /// True if the grant has expired.
    pub fn is_expired(&self, now: DateTime<Utc>) -> bool {
        self.valid_until <= now
    }

    /// Attach a signature (hex-encoded).
    pub fn with_signature(mut self, signature: impl Into<String>) -> Self {
        self.signature = signature.into();
        self
    }

    /// Whether the grant permits `source_to_target`
    /// transit (i.e. nodes in `source` reaching nodes in
    /// `target` via this grant).
    pub fn permits_direction(&self, source_to_target: bool) -> bool {
        self.direction.allows(source_to_target)
    }
}

/// On-the-wire canonical form (subset of `PeeringGrant`
/// without `signature` / `created_at`).
#[derive(Serialize)]
struct CanonicalPeeringGrant<'a> {
    grant_id: &'a PeeringGrantId,
    source: &'a MeshNetworkId,
    target: &'a MeshNetworkId,
    grantor: &'a NodeId,
    direction: PeeringDirection,
    cost: u8,
    valid_until: DateTime<Utc>,
}

/// A revocation of a previously-issued grant. Published
/// on the same gossip topic with the same `grant_id`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PeeringRevocation {
    pub grant_id: PeeringGrantId,
    pub source: MeshNetworkId,
    /// Hex-encoded signature. Verifier checks against
    /// `source`'s coordinator key (same as the grant).
    #[serde(default)]
    pub signature: String,
}

/// Snapshot of the peering-grant store for diagnostics.
#[derive(Debug, Clone)]
pub struct PeeringsSnapshot {
    pub grants: Vec<PeeringGrant>,
}

/// Trait for peering-grant storage.
///
/// The default implementation is in-memory; production
/// deployments wrap a SQLite-backed store on top of the
/// trait. The trait surface is intentionally small: we
/// only need to issue, list, and revoke.
pub trait Peerings: Send + Sync {
    /// Issue a new grant. Returns the unsigned grant; the
    /// caller signs and re-inserts via
    /// [`Peerings::attach_signature`] (or, equivalently,
    /// calls `with_signature` on the returned value).
    fn issue(&self, grant: PeeringGrant) -> CoordinatorResult<PeeringGrant>;

    /// Attach a signature to a previously-issued grant.
    /// If the grant is unknown, returns `UnknownGrant`.
    fn attach_signature(
        &self,
        grant_id: &PeeringGrantId,
        signature: String,
    ) -> CoordinatorResult<PeeringGrant>;

    /// List every *live* (non-expired) grant. Used by the
    /// gossip publisher to decide what to re-publish.
    fn list_live(&self, now: DateTime<Utc>) -> Vec<PeeringGrant>;

    /// Look up a grant by id.
    fn get(&self, grant_id: &PeeringGrantId) -> Option<PeeringGrant>;

    /// Revoke a grant. Idempotent — revoking an unknown
    /// id returns `Ok(())`.
    fn revoke(&self, grant_id: &PeeringGrantId) -> CoordinatorResult<()>;

    /// Snapshot for diagnostics.
    fn snapshot(&self) -> PeeringsSnapshot;
}

/// In-memory [`Peerings`] implementation.
#[derive(Clone)]
pub struct InMemoryPeerings {
    inner: Arc<InMemoryPeeringsInner>,
}

struct InMemoryPeeringsInner {
    grants: RwLock<HashMap<PeeringGrantId, PeeringGrant>>,
}

impl InMemoryPeerings {
    pub fn new() -> Self {
        Self {
            inner: Arc::new(InMemoryPeeringsInner {
                grants: RwLock::new(HashMap::new()),
            }),
        }
    }
}

impl Default for InMemoryPeerings {
    fn default() -> Self {
        Self::new()
    }
}

impl Peerings for InMemoryPeerings {
    fn issue(&self, grant: PeeringGrant) -> CoordinatorResult<PeeringGrant> {
        // Validate: source and target must be distinct
        // (already enforced by `new_unsigned`, but a
        // caller may have built the struct by hand).
        if grant.source == grant.target {
            return Err(CoordinatorError::PeeringSelfLoop);
        }
        if let Some(existing) = self.inner.grants.read().get(&grant.grant_id) {
            // Re-issuing the same id is treated as a
            // no-op only if the request is byte-identical.
            // This is the conservative posture — a
            // mismatched re-issue is rejected loudly.
            if existing != &grant {
                return Err(CoordinatorError::PeeringGrantIdReused {
                    grant_id: grant.grant_id.to_string(),
                });
            }
            return Ok(existing.clone());
        }
        self.inner
            .grants
            .write()
            .insert(grant.grant_id.clone(), grant.clone());
        Ok(grant)
    }

    fn attach_signature(
        &self,
        grant_id: &PeeringGrantId,
        signature: String,
    ) -> CoordinatorResult<PeeringGrant> {
        let mut grants = self.inner.grants.write();
        let entry = grants
            .get_mut(grant_id)
            .ok_or_else(|| CoordinatorError::UnknownPeeringGrant(grant_id.to_string()))?;
        entry.signature = signature;
        Ok(entry.clone())
    }

    fn list_live(&self, now: DateTime<Utc>) -> Vec<PeeringGrant> {
        self.inner
            .grants
            .read()
            .values()
            .filter(|g| !g.is_expired(now))
            .cloned()
            .collect()
    }

    fn get(&self, grant_id: &PeeringGrantId) -> Option<PeeringGrant> {
        self.inner.grants.read().get(grant_id).cloned()
    }

    fn revoke(&self, grant_id: &PeeringGrantId) -> CoordinatorResult<()> {
        self.inner.grants.write().remove(grant_id);
        Ok(())
    }

    fn snapshot(&self) -> PeeringsSnapshot {
        let now = Utc::now();
        PeeringsSnapshot {
            grants: self.list_live(now),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn nid(seed: u8) -> MeshNetworkId {
        MeshNetworkId::from_bytes(&[seed; 32]).unwrap()
    }

    fn member(seed: u8) -> NodeId {
        NodeId::from_bytes(&[seed; 32]).unwrap()
    }

    #[test]
    fn new_unsigned_rejects_self_loop() {
        let n = nid(1);
        let err = PeeringGrant::new_unsigned(n.clone(), n, member(7), Duration::from_secs(60))
            .unwrap_err();
        assert!(matches!(err, CoordinatorError::PeeringSelfLoop));
    }

    #[test]
    fn new_unsigned_caps_ttl_at_max() {
        let g = PeeringGrant::new_unsigned(
            nid(1),
            nid(2),
            member(7),
            Duration::from_secs(40 * 24 * 3600),
        )
        .unwrap();
        let cap = chrono::Duration::from_std(MAX_PEERING_TTL).unwrap();
        let actual = g.valid_until - g.created_at;
        // The cap is 30d; the request was 40d. The result
        // should be <= 30d + 1s tolerance.
        assert!(actual <= cap + chrono::Duration::seconds(1));
    }

    #[test]
    fn issue_then_get_returns_grant() {
        let p = InMemoryPeerings::new();
        let g = PeeringGrant::new_unsigned(
            nid(1),
            nid(2),
            member(7),
            Duration::from_secs(60),
        )
        .unwrap();
        let id = g.grant_id.clone();
        let issued = p.issue(g).unwrap();
        let got = p.get(&id).unwrap();
        assert_eq!(issued, got);
    }

    #[test]
    fn issue_duplicate_id_with_mismatched_payload_errors() {
        let p = InMemoryPeerings::new();
        let g1 = PeeringGrant::new_unsigned(
            nid(1),
            nid(2),
            member(7),
            Duration::from_secs(60),
        )
        .unwrap();
        let id = g1.grant_id.clone();
        p.issue(g1).unwrap();

        let g2 = PeeringGrant::new_unsigned(
            nid(1),
            nid(3),
            member(7),
            Duration::from_secs(60),
        )
        .unwrap();
        // Force the same id so the duplicate-check kicks
        // in.
        let mut g2 = g2;
        g2.grant_id = id.clone();
        let err = p.issue(g2).unwrap_err();
        assert!(matches!(err, CoordinatorError::PeeringGrantIdReused { .. }));
    }

    #[test]
    fn issue_duplicate_id_with_identical_payload_is_noop() {
        let p = InMemoryPeerings::new();
        let g1 = PeeringGrant::new_unsigned(
            nid(1),
            nid(2),
            member(7),
            Duration::from_secs(60),
        )
        .unwrap();
        let id = g1.grant_id.clone();
        p.issue(g1.clone()).unwrap();
        let g2 = p.issue(g1).unwrap();
        assert_eq!(g2.grant_id, id);
    }

    #[test]
    fn attach_signature_to_unknown_grant_errors() {
        let p = InMemoryPeerings::new();
        let err = p.attach_signature(&PeeringGrantId::new(), "deadbeef".into()).unwrap_err();
        assert!(matches!(err, CoordinatorError::UnknownPeeringGrant(_)));
    }

    #[test]
    fn attach_signature_round_trips() {
        let p = InMemoryPeerings::new();
        let g = PeeringGrant::new_unsigned(
            nid(1),
            nid(2),
            member(7),
            Duration::from_secs(60),
        )
        .unwrap();
        let id = g.grant_id.clone();
        p.issue(g).unwrap();
        let signed = p.attach_signature(&id, "abcd".into()).unwrap();
        assert_eq!(signed.signature, "abcd");
        assert_eq!(p.get(&id).unwrap().signature, "abcd");
    }

    #[test]
    fn list_live_excludes_expired() {
        let p = InMemoryPeerings::new();
        // Live
        let g_live = PeeringGrant::new_unsigned(
            nid(1),
            nid(2),
            member(7),
            Duration::from_secs(60),
        )
        .unwrap();
        p.issue(g_live).unwrap();
        // Expired (we'll backdate it)
        let mut g_expired = PeeringGrant::new_unsigned(
            nid(1),
            nid(3),
            member(7),
            Duration::from_secs(60),
        )
        .unwrap();
        let id_expired = g_expired.grant_id.clone();
        g_expired.valid_until = Utc::now() - chrono::Duration::seconds(1);
        p.issue(g_expired).unwrap();

        let now = Utc::now();
        let live = p.list_live(now);
        assert_eq!(live.len(), 1);
        assert!(live.iter().all(|g| g.grant_id != id_expired));
    }

    #[test]
    fn revoke_is_idempotent() {
        let p = InMemoryPeerings::new();
        let id = PeeringGrantId::new();
        p.revoke(&id).unwrap();
        p.revoke(&id).unwrap();
    }

    #[test]
    fn revoke_then_get_returns_none() {
        let p = InMemoryPeerings::new();
        let g = PeeringGrant::new_unsigned(
            nid(1),
            nid(2),
            member(7),
            Duration::from_secs(60),
        )
        .unwrap();
        let id = g.grant_id.clone();
        p.issue(g).unwrap();
        assert!(p.get(&id).is_some());
        p.revoke(&id).unwrap();
        assert!(p.get(&id).is_none());
    }

    #[test]
    fn direction_default_is_bidirectional() {
        let dir = PeeringDirection::default();
        assert!(dir.allows(true));
        assert!(dir.allows(false));
    }

    #[test]
    fn direction_source_to_target_only_allows_one_way() {
        let dir = PeeringDirection::SourceToTarget;
        assert!(dir.allows(true));
        assert!(!dir.allows(false));
    }

    #[test]
    fn is_expired_uses_valid_until() {
        let mut g = PeeringGrant::new_unsigned(
            nid(1),
            nid(2),
            member(7),
            Duration::from_secs(60),
        )
        .unwrap();
        let now = Utc::now();
        g.valid_until = now + chrono::Duration::seconds(1);
        assert!(!g.is_expired(now));
        g.valid_until = now - chrono::Duration::seconds(1);
        assert!(g.is_expired(now));
    }

    #[test]
    fn grant_id_default_is_unique() {
        let a = PeeringGrantId::default();
        let b = PeeringGrantId::default();
        assert_ne!(a, b);
    }

    #[test]
    fn signing_preimage_is_deterministic() {
        let g1 = PeeringGrant::new_unsigned(
            nid(1),
            nid(2),
            member(7),
            Duration::from_secs(60),
        )
        .unwrap();
        let g2 = g1.clone();
        assert_eq!(g1.signing_preimage(), g2.signing_preimage());
    }

    #[test]
    fn signing_preimage_excludes_signature_and_created_at() {
        let mut g1 = PeeringGrant::new_unsigned(
            nid(1),
            nid(2),
            member(7),
            Duration::from_secs(60),
        )
        .unwrap();
        let mut g2 = g1.clone();
        g1.signature = "first".into();
        g2.signature = "second".into();
        g1.created_at = Utc::now();
        g2.created_at = g1.created_at + chrono::Duration::seconds(10);
        // Signature and created_at must NOT affect the
        // signing preimage — otherwise the coordinator
        // could break its own signatures by changing
        // either field.
        assert_eq!(g1.signing_preimage(), g2.signing_preimage());
    }

    #[test]
    fn signing_preimage_changes_when_target_changes() {
        let g1 = PeeringGrant::new_unsigned(
            nid(1),
            nid(2),
            member(7),
            Duration::from_secs(60),
        )
        .unwrap();
        let g2 = PeeringGrant::new_unsigned(
            nid(1),
            nid(3),
            member(7),
            Duration::from_secs(60),
        )
        .unwrap();
        assert_ne!(g1.signing_preimage(), g2.signing_preimage());
    }

    #[test]
    fn signing_digest_is_32_bytes() {
        let g = PeeringGrant::new_unsigned(
            nid(1),
            nid(2),
            member(7),
            Duration::from_secs(60),
        )
        .unwrap();
        let d = g.signing_digest();
        assert_eq!(d.len(), 32);
    }

    #[test]
    fn snapshot_includes_live_grants() {
        let p = InMemoryPeerings::new();
        p.issue(
            PeeringGrant::new_unsigned(
                nid(1),
                nid(2),
                member(7),
                Duration::from_secs(60),
            )
            .unwrap(),
        )
        .unwrap();
        let snap = p.snapshot();
        assert_eq!(snap.grants.len(), 1);
    }

    #[test]
    fn permits_direction_propagates_through_grant() {
        let mut g = PeeringGrant::new_unsigned(
            nid(1),
            nid(2),
            member(7),
            Duration::from_secs(60),
        )
        .unwrap();
        g.direction = PeeringDirection::SourceToTarget;
        assert!(g.permits_direction(true));
        assert!(!g.permits_direction(false));
    }
}
