package a3net.ffi.uniffi

import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import kotlinx.coroutines.withTimeoutOrNull

/**
 * A3NetUniffiDemo.kt — Kotlin / Android consumer for the
 * uniffi surface of `a3net-ffi`.
 *
 * The companion Rust crate exposes a UDL at
 * `crates/a3net-ffi/src/a3net.udl` (generated by uniffi when
 * the `--features uniffi` build is active). Generate the
 * Kotlin bindings with:
 *
 *     cargo run -p a3net-ffi --features uniffi -- uniffi \
 *         generate src/a3net.udl --language kotlin \
 *         --out-dir bindings/kotlin
 *
 * The generated module declares `AdnetHandle`, `AdnetError`
 * and the record types. This file *demonstrates* how an
 * Android app would consume them: a coroutine-driven
 * `ViewModel`, a `StateFlow<State>` the UI subscribes to,
 * and `try { … } catch (e: AdnetError)` for the typed error
 * path.
 *
 * To keep this file standalone — compilable in any IDE that
 * points at the uniffi bindings — the bindings below are
 * declared as `expect object`/`expect class` placeholders.
 * The real classes are produced by `uniffi-bindgen` and live
 * next to this file at build time; simply delete the
 * placeholders and let the bindings take over.
 */

// ---------------------------------------------------------------------------
// Uniffi stubs — replaced by `uniffi-bindgen` output at build time
// ---------------------------------------------------------------------------

sealed class AdnetError(message: String) : Throwable(message) {
    class InvalidArgument(message: String) : AdnetError(message)
    class InvalidUtf8(message: String) : AdnetError(message)
    class InvalidJson(message: String) : AdnetError(message)
    class Node(message: String) : AdnetError(message)
    class Runtime(message: String) : AdnetError(message)
    class Feature(message: String) : AdnetError(message)
    class Io(message: String) : AdnetError(message)
    class NotFound(message: String) : AdnetError(message)
    class Profile(message: String) : AdnetError(message)
}

data class BlobPutInfo(val hash: String, val ticket: String, val size: ULong)
data class BlobFetchInfo(val hash: String, val size: ULong)
data class IpnsPublishInfo(val name: String)
data class IpnsResolveInfo(val name: String, val value: String)
data class NodeInfo(val nodeId: String, val uptimeSecs: ULong)
data class NodeMetricsInfo(
    val peerCount: UInt,
    val blobCount: UInt,
    val gossipTopics: UInt,
    val uptimeSecs: ULong,
)

/**
 * Stub of the uniffi object. Replace with the
 * `uniffi-bindgen`-generated `AdnetHandle` once the bindings
 * are built. The shape mirrors the Rust source so any caller
 * can rely on the names.
 *
 * Note: the placeholder `gossipSubscribe` method from the
 * v0.1 demo was removed when the uniffi callback interface
 * machinery landed in a follow-up PR. Subscribe-style APIs
 * are exposed as top-level functions, e.g.
 * `a3netFfiPlaceholderGossipSubscribe(topic)`.
 */
expect class AdnetHandle(dataDir: String) {
    fun ensureBooted(): String
    fun nodeId(): String
    fun info(): NodeInfo
    fun putBytes(data: ByteArray): BlobPutInfo
    fun fetchTicket(ticket: String): BlobFetchInfo
    fun ipnsPublish(name: String, value: String): IpnsPublishInfo
    fun ipnsResolve(name: String): IpnsResolveInfo
    fun metrics(): NodeMetricsInfo
    fun destroy()
}

fun a3netVersion(): UInt = 0u

/**
 * Placeholder gossip subscription. Returns the topic name as a
 * stable subscription id until the full callback interface is
 * wired through `uniffi::CallbackInterface`. The Rust side
 * declares this as `a3net_ffi_placeholder_gossip_subscribe`.
 */
fun a3netFfiPlaceholderGossipSubscribe(topic: String): String =
    if (topic.isEmpty()) throw AdnetError.InvalidArgument("topic must not be empty")
    else "gossip::$topic"

// ---------------------------------------------------------------------------
// ViewModel — coroutine-driven, exposes StateFlow<State>
// ---------------------------------------------------------------------------

/**
 * State the UI can render. `Error` carries the typed
 * `AdnetError` so the activity can `when (state) { … }`
 * over the variants in a Kotlin-idiomatic way.
 */
sealed class State {
    object Idle : State()
    object Booting : State()
    data class Ready(val nodeId: String) : State()
    data class Error(val error: AdnetError) : State()
}

class AdnetDemoViewModel(dataDir: String) {
    private val scope = CoroutineScope(SupervisorJob() + Dispatchers.Default)
    private val _state = MutableStateFlow<State>(State.Idle)
    val state: StateFlow<State> = _state.asStateFlow()

    private var handle: AdnetHandle? = null
    private val dir = dataDir

    fun boot() {
        scope.launch {
            _state.value = State.Booting
            try {
                val h = withContext(Dispatchers.IO) { AdnetHandle(dir) }
                val id = withContext(Dispatchers.IO) { h.ensureBooted() }
                handle = h
                _state.value = State.Ready(id)
            } catch (e: AdnetError) {
                _state.value = State.Error(e)
            }
        }
    }

    fun putBytes(data: ByteArray): Result<BlobPutInfo> =
        runOrError { handle?.putBytes(data) }

    fun resolve(name: String): Result<IpnsResolveInfo> =
        runOrError { handle?.ipnsResolve(name) }

    fun metrics(): Result<NodeMetricsInfo> =
        runOrError { handle?.metrics() }

    private inline fun <T> runOrError(block: () -> T?): Result<T> = try {
        val v = block() ?: return Result.failure(
            AdnetError.Runtime("node not booted"),
        )
        Result.success(v)
    } catch (e: AdnetError) {
        Result.failure(e)
    }

    fun shutdown() {
        scope.launch {
            try {
                handle?.destroy()
            } catch (_: AdnetError) {
                // best-effort: drop the handle silently.
            }
            handle = null
        }
    }
}

// ---------------------------------------------------------------------------
// Minimal smoke-test driver
// ---------------------------------------------------------------------------

/**
 * Single-class entry point. Boot the handle, print the
 * node id, hash a small payload, resolve an IPNS name. If
 * the bindings are absent (this file compiled in isolation),
 * every call surfaces `AdnetError.Feature` — useful for CI
 * gating the binding-generation step.
 */
suspend fun runAdnetDemo(dataDir: String) {
    val vm = AdnetDemoViewModel(dataDir)
    vm.boot()
    // `boot()` is fire-and-forget on the internal scope;
    // wait until `state` settles into a terminal value
    // (Ready / Error) before reading it. The 30 s cap is
    // generous for a cold start on Android emulators.
    val settled = withTimeoutOrNull(BOOT_TIMEOUT_MS) {
        vm.state.first { it is State.Ready || it is State.Error }
    }
    when (val s = settled ?: vm.state.value) {
        is State.Ready -> println("booted: ${s.nodeId}")
        is State.Error -> println("error: ${s.error.message}")
        else           -> println("still booting…")
    }
    // Quick sanity: hash a 4-byte payload and confirm the
    // ticket is non-empty. We don't care about correctness
    // — only that the FFI round-trip succeeds.
    val info = vm.putBytes(byteArrayOf(1, 2, 3, 4))
    println("put: $info")
    val resolved = vm.resolve("a3net://example")
    println("resolve: $resolved")
    vm.shutdown()
}

private const val BOOT_TIMEOUT_MS = 30_000L