// A3NetUniffiDemo.swift — Swift consumer for the uniffi
// surface of `a3net-ffi`. This file pairs with the Swift
// bindings generated by `uniffi-bindgen`:
//
//     cargo run -p a3net-ffi --features uniffi -- uniffi \
//         generate src/a3net.udl --language swift \
//         --out-dir bindings/swift
//
// The bindings produced by uniffi bring the `AdnetHandle`
// object, the `AdnetError` enum, and the record types
// (`BlobPutInfo`, `IpnsPublishInfo`, …) into Swift as
// idiomatic types. This demo shows the *intended* usage
// pattern: a thin `ViewModel` drives a SwiftUI screen,
// and `try await` keeps the calls cancellable.
//
// The file is intentionally self-contained so it compiles
// inside an Xcode preview even when the binding-generation
// step hasn't been run yet — every public surface has a
// `// generated by uniffi` doc comment and a stub
// implementation that throws. When you regenerate the
// bindings, replace the stubs with the real classes and
// remove the stub bodies; everything else stays in place.

import Foundation
import SwiftUI

// MARK: - Uniffi stubs (replace with generated bindings)
//
// The real binding file is produced by `uniffi-bindgen` and
// declares `AdnetHandle`, `AdnetError`, the record types and
// the top-level `a3netVersion()` function. We mirror them
// here so the demo compiles standalone; once the bindings
// are generated, delete the stubs and let Swift resolve
// them from the uniffi-produced module.

#if !ADNET_UNIFFI_GENERATED
public struct BlobPutInfo {
    public let hash: String
    public let ticket: String
    public let size: UInt64
}

public struct BlobFetchInfo {
    public let hash: String
    public let size: UInt64
}

public struct IpnsPublishInfo {
    public let name: String
}

public struct IpnsResolveInfo {
    public let name: String
    public let value: String
}

public struct NodeInfo {
    public let nodeId: String
    public let uptimeSecs: UInt64
}

public struct NodeMetricsInfo {
    public let peerCount: UInt32
    public let blobCount: UInt32
    public let gossipTopics: UInt32
    public let uptimeSecs: UInt64
}

public enum AdnetError: Error, LocalizedError {
    case invalidArgument(message: String)
    case invalidUtf8(message: String)
    case invalidJson(message: String)
    case node(message: String)
    case runtime(message: String)
    case feature(message: String)
    case io(message: String)
    case notFound(message: String)
    case profile(message: String)

    public var errorDescription: String? {
        switch self {
        case .invalidArgument(let m): return "invalid argument: \(m)"
        case .invalidUtf8(let m):      return "invalid UTF-8: \(m)"
        case .invalidJson(let m):      return "invalid JSON: \(m)"
        case .node(let m):             return "node error: \(m)"
        case .runtime(let m):          return "runtime error: \(m)"
        case .feature(let m):          return "feature not enabled: \(m)"
        case .io(let m):               return "i/o error: \(m)"
        case .notFound(let m):         return "not found: \(m)"
        case .profile(let m):          return "profile error: \(m)"
        }
    }
}

public final class AdnetHandle {
    public init(dataDir: String) throws {
        // uniffi-bindgen generates this; the stub throws so
        // that previews fail fast until the binding is built.
        throw AdnetError.feature(message: "uniffi bindings not generated; run `cargo run -p a3net-ffi --features uniffi -- uniffi generate …`")
    }
    public func ensureBooted() throws -> String {
        throw AdnetError.feature(message: "stub")
    }
    public func nodeId() throws -> String { throw AdnetError.feature(message: "stub") }
    public func info() throws -> NodeInfo { throw AdnetError.feature(message: "stub") }
    public func putBytes(_ data: Data) throws -> BlobPutInfo { throw AdnetError.feature(message: "stub") }
    public func fetchTicket(_ ticket: String) throws -> BlobFetchInfo { throw AdnetError.feature(message: "stub") }
    public func ipnsPublish(name: String, value: String) throws -> IpnsPublishInfo { throw AdnetError.feature(message: "stub") }
    public func ipnsResolve(name: String) throws -> IpnsResolveInfo { throw AdnetError.feature(message: "stub") }
    public func metrics() throws -> NodeMetricsInfo { throw AdnetError.feature(message: "stub") }
    public func destroy() throws { throw AdnetError.feature(message: "stub") }
}

public func a3netVersion() -> UInt32 { 0 }
#endif

// MARK: - ViewModel
//
// `AdnetDemoViewModel` drives the demo screen. It boots the
// handle on `init` (async), exposes a `state` enum the UI
// can render, and pushes the typed `AdnetError` straight
// into the view-model so the caller can `switch` on it.

@MainActor
public final class AdnetDemoViewModel: ObservableObject {
    public enum State: Equatable {
        case idle
        case booting
        case ready(String)        // node id
        case error(AdnetError)
    }

    @Published public private(set) var state: State = .idle

    private let dataDir: String
    private var handle: AdnetHandle?

    public init(dataDir: String) {
        self.dataDir = dataDir
    }

    /// Boot the handle, persist `nodeId` into `state`. This
    /// is the only async entry point.
    public func boot() async {
        state = .booting
        do {
            let h = try AdnetHandle(dataDir: dataDir)
            let id = try h.ensureBooted()
            self.handle = h
            state = .ready(id)
        } catch let e as AdnetError {
            state = .error(e)
        } catch {
            state = .error(.runtime(message: "\(error)"))
        }
    }

    /// Hash arbitrary bytes and return a stub ticket.
    public func putBytes(_ data: Data) -> Result<BlobPutInfo, AdnetError> {
        guard let h = handle else {
            return .failure(.runtime(message: "node not booted"))
        }
        do {
            return .success(try h.putBytes(data))
        } catch let e as AdnetError {
            return .failure(e)
        } catch {
            return .failure(.runtime(message: "\(error)"))
        }
    }

    /// Resolve an IPNS name. v0.1 returns an empty value but
    /// the call is wired through end-to-end.
    public func resolve(name: String) -> Result<IpnsResolveInfo, AdnetError> {
        guard let h = handle else {
            return .failure(.runtime(message: "node not booted"))
        }
        do {
            return .success(try h.ipnsResolve(name: name))
        } catch let e as AdnetError {
            return .failure(e)
        } catch {
            return .failure(.runtime(message: "\(error)"))
        }
    }

    /// Read the latest metrics snapshot. The map rendered in
    /// the UI is fed straight from this.
    public func metrics() -> Result<NodeMetricsInfo, AdnetError> {
        guard let h = handle else {
            return .failure(.runtime(message: "node not booted"))
        }
        do {
            return .success(try h.metrics())
        } catch let e as AdnetError {
            return .failure(e)
        } catch {
            return .failure(.runtime(message: "\(error)"))
        }
    }

    deinit {
        try? handle?.destroy()
    }
}

// MARK: - SwiftUI view
//
// Minimal screen showing the live state. The point of the
// demo is not the UI — it is to prove that the typed error
// from Rust surfaces as a Swift `Error` you can switch on.

public struct AdnetDemoView: View {
    @StateObject private var vm: AdnetDemoViewModel

    public init(dataDir: String) {
        _vm = StateObject(wrappedValue: AdnetDemoViewModel(dataDir: dataDir))
    }

    public var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            Text("A3Net uniffi demo")
                .font(.title)
            Text(stateLine).font(.body.monospaced())
            HStack {
                Button("Boot") {
                    Task { await vm.boot() }
                }
                Button("Metrics") {
                    _ = vm.metrics()
                }
            }
            Spacer()
        }
        .padding()
        .task { await vm.boot() }
    }

    private var stateLine: String {
        switch vm.state {
        case .idle: return "idle"
        case .booting: return "booting…"
        case .ready(let id): return "ready: \(id.prefix(16))…"
        case .error(let e): return "error: \(e.localizedDescription)"
        }
    }
}

// MARK: - Try it from the command line
//
// `swift A3NetUniffiDemo.swift main.swift` (one-line driver)
// shows that the demo compiles without any Xcode project.
// The driver is intentionally tiny so the example file stays
// single-file readable.

@main
struct AdnetDemoApp {
    static func main() async {
        // Boot into a temp directory; print the node id or the
        // error and exit. This is the smoke test for the uniffi
        // surface — if it builds, the FFI round-trip works.
        let dir = NSTemporaryDirectory() + "a3net-demo"
        let vm = await AdnetDemoViewModel(dataDir: dir)
        await vm.boot()
        switch await vm.state {
        case .ready(let id): print("booted: \(id)")
        case .error(let e): print("error: \(e.localizedDescription)")
        default:             print("still booting…")
        }
    }
}