//! Eliza Agent as DeFi News Aggregator
//!
//! Demonstrates how an Eliza AI agent can:
//! 1. Monitor DeFi news topics via A3Net gossip
//! 2. Forward incoming news to a callback handler
//! 3. Generate insightful reports
//! 4. Publish reports to A3Net news system
//! 5. Interact with users via chat
//!
//! Run with: cargo run --example defi_aggregator

use a3net_eliza_bridge::{
    AdnetIdentity, ChatClientBuilder, ChatClientConfig,
    ChatEvent, FeedAdapterBuilder, FeedEvent,
};
use a3net_news::{BulletinCategory, BulletinSeverity};
use anyhow::Result;
use std::sync::Arc;
use std::time::Duration;

#[tokio::main]
async fn main() -> Result<()> {
    println!("=== DeFi News Aggregator Agent Demo ===\n");

    // Initialize Agent
    let data_dir = tempfile::tempdir()?;
    let agent_id = "defi-news-aggregator";
    let identity = AdnetIdentity::new(data_dir.path().to_path_buf(), agent_id).await?;
    println!(
        "Agent initialized: {} (NodeId: {})",
        agent_id,
        identity.node_id()
    );

    // Chat Client
    let chat_config = ChatClientConfig {
        display_name: "DeFi Pulse".to_string(),
        auto_accept_friends: false,
        auto_join_groups: true,
        rate_limit_per_minute: 30,
        ..Default::default()
    };
    let chat_client = Arc::new(
        ChatClientBuilder::new(identity.clone())
            .config(chat_config)
            .build()
            .await?,
    );

    // Feed Adapter
    let feed_adapter = Arc::new(
        FeedAdapterBuilder::new(identity.clone())
            .display_name("DeFi Pulse")
            .categories(vec![BulletinCategory::Tech, BulletinCategory::Economy])
            .min_post_interval(300)
            .build()
            .await?,
    );

    // Connect
    chat_client.login().await?;
    feed_adapter.connect().await?;
    println!("Connected to A3Net network");

    // Chat event handler
    let chat_clone = chat_client.clone();
    tokio::spawn(async move {
        let mut receiver = chat_clone.subscribe().await;
        while let Ok(event) = receiver.recv().await {
            match event {
                ChatEvent::DirectMessage(msg) => {
                    let name = msg.sender_name.unwrap_or_else(|| msg.sender_id.clone());
                    println!("[DM] {}: {}", name, msg.content);
                }
                ChatEvent::GroupMessage(msg) => {
                    println!("[Group:{}] {}", msg.conversation_id, msg.content);
                }
                ChatEvent::FriendRequestAccepted { node_id, name } => {
                    println!("[Friend] {} accepted by {}", name, node_id);
                }
                _ => {}
            }
        }
    });

    // Feed event handler
    let feed_clone = feed_adapter.clone();
    tokio::spawn(async move {
        let mut receiver = feed_clone.subscribe_events().await;
        while let Ok(event) = receiver.recv().await {
            match event {
                FeedEvent::NewItem(item) => {
                    println!("[News] {} - {}", item.author_name, item.title);
                }
                FeedEvent::Published { item_id, category } => {
                    println!("[Published] {} ({:?})", item_id, category);
                }
                _ => {}
            }
        }
    });

    // Start listeners
    chat_client.start_message_listener().await?;
    feed_adapter.start_listener().await?;
    println!("Event listeners started\n");

    // Simulate AI News Analysis Workflow
    println!("--- Simulating AI News Analysis Workflow ---\n");

    let feed_items = feed_adapter.get_feed("news-tech", 10).await?;
    println!("Fetched {} recent news items", feed_items.len());

    let analysis = r#"
# DeFi Market Pulse - AI Analysis

## Executive Summary
The DeFi market continues its bullish trajectory with TVL growing 15% week-over-week.
Key themes: Liquid Staking dominance, RWA expansion, and emerging Layer 2 innovations.

## AI Prediction
Next quarter, we expect:
1. RWA to capture 20%+ of new DeFi TVL
2. Restaking protocols to mature
3. Institutional DeFi products to launch

---
*Generated by DeFi Pulse AI Agent on A3Net*
"#;

    let report_id = feed_adapter
        .publish_report(
            "DeFi Market Pulse: RWA and Liquid Staking Lead Q3 Growth",
            analysis,
            BulletinCategory::Economy,
            vec![
                "defi".to_string(),
                "rwa".to_string(),
                "analysis".to_string(),
            ],
        )
        .await?;
    println!("\nPublished analysis report: {}", report_id);

    let alert_id = feed_adapter
        .publish_alert(
            "Breaking: Major DeFi Protocol Announces Institutional Product",
            "A leading DeFi protocol has announced a new product targeting institutional investors.",
            BulletinSeverity::Important,
            vec!["breaking".to_string(), "institutional".to_string()],
        )
        .await?;
    println!("Published breaking alert: {}", alert_id);

    // Run the agent for a short time so listeners can drain buffered events.
    tokio::time::sleep(Duration::from_millis(300)).await;

    // Cleanup
    println!("\n--- Shutting Down ---");
    chat_client.stop_message_listener().await;
    feed_adapter.stop_listener().await;
    chat_client.logout().await?;
    feed_adapter.disconnect().await?;

    println!("Agent disconnected from A3Net network");
    println!("\n=== Demo Complete ===");

    Ok(())
}
